version: '3.8'

services:
  notes-app:
    build:
      context: .
    container_name: notes-app
    restart: unless-stopped
    ports:
      - '5000:5000'
      - '3000:3000'
    depends_on:
      - mongo
    environment:
      MONGO_URI: 'mongodb://mongo:27017/notes_db'  # Connection string to MongoDB

  mongo:
    image: mongo:latest
    container_name: mongo
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
